### ISSUE TITLE
Create unit tests for src/util.js that cover the basic functionality of this file.

### ISSUE THREAD

**Issue by ILOVEPIE** [SABRE-JS/SABRE.js#23]
We need unit tests for `src/util.js` following a similar style to the ones for `src/color.js` which may be found in `src/__tests__/color.test.js`

**Comment by eLeontev** [comment]
Could you provide the scope of `basic` functionality (list of methods) need to be tested? If you also could provide the test data for complex of them it would be great.

**Comment by eLeontev** [comment]
Hi, I covered `#performTransition` and `#stringEqualsCaseInsensitive` methods.

For `lehex` and `canvas2blob` please make them public to be able to test. For now they are private and cannot be tested since redefined by default method `toBlob`

![image](https://user-images.githubusercontent.com/15786916/137595002-bfdd2d44-0229-4042-b83b-a92bc44cf372.png)


More other I'm wondering if they are used due to assignment to native `#toBlob`

**Comment by ILOVEPIE** [comment]
It's a polyfill, in case the browser doesn't support toBlob.
